apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: application
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: stats
      protocol: TCP
      port: 9113
      targetPort: 9113