apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web
  namespace: application
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  namespaceSelector:
    matchNames:
      - application
  endpoints:
    - port: stats
      path: /metrics