apiVersion: v1
kind: Pod
metadata:
    name: web
    labels:
        app: web
spec:
    containers:
    - name: web
      image: jndogan/kube-intro:latest
      volumeMounts:
        - name: app
          mountPath: /app
    initContainers:
    - name: init-gen-index
      image: busybox:latest
      volumeMounts:
      - name: app
        mountPath: /app
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumes:
    - name: app
      emptyDir: {}